version: 2
updates:
  # npm 依赖更新
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Shanghai'
    open-pull-requests-limit: 10
    reviewers:
      - 'UE-DND'
    commit-message:
      prefix: '⬆️'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automated'
    # 自动合并小版本和补丁版本更新
    versioning-strategy: increase

  # GitHub Actions 更新
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Shanghai'
    open-pull-requests-limit: 5
    commit-message:
      prefix: '⬆️ [CI]'
    labels:
      - 'dependencies'
      - 'ci'
      - 'automated'
